//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETNA.MVC.LogisticaServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlmacenDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.LO")]
    [System.SerializableAttribute()]
    public partial class AlmacenDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaSolicitudEntradaDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.LO")]
    [System.SerializableAttribute()]
    public partial class ListaSolicitudEntradaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaElaboracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEntradaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaElaboracion {
            get {
                return this.FechaElaboracionField;
            }
            set {
                if ((this.FechaElaboracionField.Equals(value) != true)) {
                    this.FechaElaboracionField = value;
                    this.RaisePropertyChanged("FechaElaboracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpleado {
            get {
                return this.NombreEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpleadoField, value) != true)) {
                    this.NombreEmpleadoField = value;
                    this.RaisePropertyChanged("NombreEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEntrada {
            get {
                return this.TipoEntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEntradaField, value) != true)) {
                    this.TipoEntradaField = value;
                    this.RaisePropertyChanged("TipoEntrada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudEntradaDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.LO")]
    [System.SerializableAttribute()]
    public partial class SolicitudEntradaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ETNA.MVC.LogisticaServices.DetalleSolicitudEntradaDto[] DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaElaboracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEntradaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETNA.MVC.LogisticaServices.DetalleSolicitudEntradaDto[] Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaElaboracion {
            get {
                return this.FechaElaboracionField;
            }
            set {
                if ((this.FechaElaboracionField.Equals(value) != true)) {
                    this.FechaElaboracionField = value;
                    this.RaisePropertyChanged("FechaElaboracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpleado {
            get {
                return this.NombreEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpleadoField, value) != true)) {
                    this.NombreEmpleadoField = value;
                    this.RaisePropertyChanged("NombreEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEntrada {
            get {
                return this.TipoEntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEntradaField, value) != true)) {
                    this.TipoEntradaField = value;
                    this.RaisePropertyChanged("TipoEntrada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleSolicitudEntradaDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.LO")]
    [System.SerializableAttribute()]
    public partial class DetalleSolicitudEntradaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto {
            get {
                return this.NombreProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProductoField, value) != true)) {
                    this.NombreProductoField = value;
                    this.RaisePropertyChanged("NombreProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaSolicitudSalidaDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.LO")]
    [System.SerializableAttribute()]
    public partial class ListaSolicitudSalidaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaElaboracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoSalidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionEntrega {
            get {
                return this.DireccionEntregaField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionEntregaField, value) != true)) {
                    this.DireccionEntregaField = value;
                    this.RaisePropertyChanged("DireccionEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaElaboracion {
            get {
                return this.FechaElaboracionField;
            }
            set {
                if ((this.FechaElaboracionField.Equals(value) != true)) {
                    this.FechaElaboracionField = value;
                    this.RaisePropertyChanged("FechaElaboracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpleado {
            get {
                return this.NombreEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpleadoField, value) != true)) {
                    this.NombreEmpleadoField = value;
                    this.RaisePropertyChanged("NombreEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocialDestinatario {
            get {
                return this.RazonSocialDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialDestinatarioField, value) != true)) {
                    this.RazonSocialDestinatarioField = value;
                    this.RaisePropertyChanged("RazonSocialDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSalida {
            get {
                return this.TipoSalidaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSalidaField, value) != true)) {
                    this.TipoSalidaField = value;
                    this.RaisePropertyChanged("TipoSalida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudSalidaDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.LO")]
    [System.SerializableAttribute()]
    public partial class SolicitudSalidaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ETNA.MVC.LogisticaServices.DetalleSolicitudSalidaDto[] DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaElaboracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoSalidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETNA.MVC.LogisticaServices.DetalleSolicitudSalidaDto[] Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionEntrega {
            get {
                return this.DireccionEntregaField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionEntregaField, value) != true)) {
                    this.DireccionEntregaField = value;
                    this.RaisePropertyChanged("DireccionEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaElaboracion {
            get {
                return this.FechaElaboracionField;
            }
            set {
                if ((this.FechaElaboracionField.Equals(value) != true)) {
                    this.FechaElaboracionField = value;
                    this.RaisePropertyChanged("FechaElaboracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpleado {
            get {
                return this.NombreEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpleadoField, value) != true)) {
                    this.NombreEmpleadoField = value;
                    this.RaisePropertyChanged("NombreEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocialDestinatario {
            get {
                return this.RazonSocialDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialDestinatarioField, value) != true)) {
                    this.RazonSocialDestinatarioField = value;
                    this.RaisePropertyChanged("RazonSocialDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSalida {
            get {
                return this.TipoSalidaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSalidaField, value) != true)) {
                    this.TipoSalidaField = value;
                    this.RaisePropertyChanged("TipoSalida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleSolicitudSalidaDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.LO")]
    [System.SerializableAttribute()]
    public partial class DetalleSolicitudSalidaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto {
            get {
                return this.NombreProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProductoField, value) != true)) {
                    this.NombreProductoField = value;
                    this.RaisePropertyChanged("NombreProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoDto", Namespace="http://schemas.datacontract.org/2004/07/ETNA.DTOs.LO")]
    [System.SerializableAttribute()]
    public partial class EmpleadoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogisticaServices.IEntradasYSalidasService")]
    public interface IEntradasYSalidasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerAlmacenesPorEmpleado", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerAlmacenesPorEmpleadoResponse")]
        ETNA.MVC.LogisticaServices.AlmacenDto[] ObtenerAlmacenesPorEmpleado(int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerAlmacenesPorEmpleado", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerAlmacenesPorEmpleadoResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.AlmacenDto[]> ObtenerAlmacenesPorEmpleadoAsync(int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudesEntrada", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudesEntradaResponse")]
        ETNA.MVC.LogisticaServices.ListaSolicitudEntradaDto[] ObtenerSolicitudesEntrada(int idSolicitud, int estadoSolicitud, System.DateTime fechaInicio, System.DateTime fechaFin, int idEmpleado, int tipoEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudesEntrada", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudesEntradaResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.ListaSolicitudEntradaDto[]> ObtenerSolicitudesEntradaAsync(int idSolicitud, int estadoSolicitud, System.DateTime fechaInicio, System.DateTime fechaFin, int idEmpleado, int tipoEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudEntrada", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudEntradaResponse")]
        ETNA.MVC.LogisticaServices.SolicitudEntradaDto ObtenerSolicitudEntrada(int idSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudEntrada", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudEntradaResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.SolicitudEntradaDto> ObtenerSolicitudEntradaAsync(int idSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/GenerarGuiaEntrada", ReplyAction="http://tempuri.org/IEntradasYSalidasService/GenerarGuiaEntradaResponse")]
        bool GenerarGuiaEntrada(int idSolicitud, int idAlmacen, int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/GenerarGuiaEntrada", ReplyAction="http://tempuri.org/IEntradasYSalidasService/GenerarGuiaEntradaResponse")]
        System.Threading.Tasks.Task<bool> GenerarGuiaEntradaAsync(int idSolicitud, int idAlmacen, int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/RechazarGuiaEntrada", ReplyAction="http://tempuri.org/IEntradasYSalidasService/RechazarGuiaEntradaResponse")]
        bool RechazarGuiaEntrada(int idSolicitud, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/RechazarGuiaEntrada", ReplyAction="http://tempuri.org/IEntradasYSalidasService/RechazarGuiaEntradaResponse")]
        System.Threading.Tasks.Task<bool> RechazarGuiaEntradaAsync(int idSolicitud, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudesSalida", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudesSalidaResponse")]
        ETNA.MVC.LogisticaServices.ListaSolicitudSalidaDto[] ObtenerSolicitudesSalida(int idSolicitud, int estadoSolicitud, System.DateTime fechaInicio, System.DateTime fechaFin, int idEmpleado, string tipoSalida, string direccionEntrega, string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudesSalida", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudesSalidaResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.ListaSolicitudSalidaDto[]> ObtenerSolicitudesSalidaAsync(int idSolicitud, int estadoSolicitud, System.DateTime fechaInicio, System.DateTime fechaFin, int idEmpleado, string tipoSalida, string direccionEntrega, string razonSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudSalida", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudSalidaResponse")]
        ETNA.MVC.LogisticaServices.SolicitudSalidaDto ObtenerSolicitudSalida(int idSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudSalida", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerSolicitudSalidaResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.SolicitudSalidaDto> ObtenerSolicitudSalidaAsync(int idSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/GenerarGuiaSalida", ReplyAction="http://tempuri.org/IEntradasYSalidasService/GenerarGuiaSalidaResponse")]
        bool GenerarGuiaSalida(int idSolicitud, int idAlmacen, int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/GenerarGuiaSalida", ReplyAction="http://tempuri.org/IEntradasYSalidasService/GenerarGuiaSalidaResponse")]
        System.Threading.Tasks.Task<bool> GenerarGuiaSalidaAsync(int idSolicitud, int idAlmacen, int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/RechazarGuiaSalida", ReplyAction="http://tempuri.org/IEntradasYSalidasService/RechazarGuiaSalidaResponse")]
        bool RechazarGuiaSalida(int idSolicitud, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/RechazarGuiaSalida", ReplyAction="http://tempuri.org/IEntradasYSalidasService/RechazarGuiaSalidaResponse")]
        System.Threading.Tasks.Task<bool> RechazarGuiaSalidaAsync(int idSolicitud, string observaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerEmpleados", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerEmpleadosResponse")]
        ETNA.MVC.LogisticaServices.EmpleadoDto[] ObtenerEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntradasYSalidasService/ObtenerEmpleados", ReplyAction="http://tempuri.org/IEntradasYSalidasService/ObtenerEmpleadosResponse")]
        System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.EmpleadoDto[]> ObtenerEmpleadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntradasYSalidasServiceChannel : ETNA.MVC.LogisticaServices.IEntradasYSalidasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntradasYSalidasServiceClient : System.ServiceModel.ClientBase<ETNA.MVC.LogisticaServices.IEntradasYSalidasService>, ETNA.MVC.LogisticaServices.IEntradasYSalidasService {
        
        public EntradasYSalidasServiceClient() {
        }
        
        public EntradasYSalidasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntradasYSalidasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntradasYSalidasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntradasYSalidasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ETNA.MVC.LogisticaServices.AlmacenDto[] ObtenerAlmacenesPorEmpleado(int idEmpleado) {
            return base.Channel.ObtenerAlmacenesPorEmpleado(idEmpleado);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.AlmacenDto[]> ObtenerAlmacenesPorEmpleadoAsync(int idEmpleado) {
            return base.Channel.ObtenerAlmacenesPorEmpleadoAsync(idEmpleado);
        }
        
        public ETNA.MVC.LogisticaServices.ListaSolicitudEntradaDto[] ObtenerSolicitudesEntrada(int idSolicitud, int estadoSolicitud, System.DateTime fechaInicio, System.DateTime fechaFin, int idEmpleado, int tipoEntrada) {
            return base.Channel.ObtenerSolicitudesEntrada(idSolicitud, estadoSolicitud, fechaInicio, fechaFin, idEmpleado, tipoEntrada);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.ListaSolicitudEntradaDto[]> ObtenerSolicitudesEntradaAsync(int idSolicitud, int estadoSolicitud, System.DateTime fechaInicio, System.DateTime fechaFin, int idEmpleado, int tipoEntrada) {
            return base.Channel.ObtenerSolicitudesEntradaAsync(idSolicitud, estadoSolicitud, fechaInicio, fechaFin, idEmpleado, tipoEntrada);
        }
        
        public ETNA.MVC.LogisticaServices.SolicitudEntradaDto ObtenerSolicitudEntrada(int idSolicitud) {
            return base.Channel.ObtenerSolicitudEntrada(idSolicitud);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.SolicitudEntradaDto> ObtenerSolicitudEntradaAsync(int idSolicitud) {
            return base.Channel.ObtenerSolicitudEntradaAsync(idSolicitud);
        }
        
        public bool GenerarGuiaEntrada(int idSolicitud, int idAlmacen, int idEmpleado) {
            return base.Channel.GenerarGuiaEntrada(idSolicitud, idAlmacen, idEmpleado);
        }
        
        public System.Threading.Tasks.Task<bool> GenerarGuiaEntradaAsync(int idSolicitud, int idAlmacen, int idEmpleado) {
            return base.Channel.GenerarGuiaEntradaAsync(idSolicitud, idAlmacen, idEmpleado);
        }
        
        public bool RechazarGuiaEntrada(int idSolicitud, string observaciones) {
            return base.Channel.RechazarGuiaEntrada(idSolicitud, observaciones);
        }
        
        public System.Threading.Tasks.Task<bool> RechazarGuiaEntradaAsync(int idSolicitud, string observaciones) {
            return base.Channel.RechazarGuiaEntradaAsync(idSolicitud, observaciones);
        }
        
        public ETNA.MVC.LogisticaServices.ListaSolicitudSalidaDto[] ObtenerSolicitudesSalida(int idSolicitud, int estadoSolicitud, System.DateTime fechaInicio, System.DateTime fechaFin, int idEmpleado, string tipoSalida, string direccionEntrega, string razonSocial) {
            return base.Channel.ObtenerSolicitudesSalida(idSolicitud, estadoSolicitud, fechaInicio, fechaFin, idEmpleado, tipoSalida, direccionEntrega, razonSocial);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.ListaSolicitudSalidaDto[]> ObtenerSolicitudesSalidaAsync(int idSolicitud, int estadoSolicitud, System.DateTime fechaInicio, System.DateTime fechaFin, int idEmpleado, string tipoSalida, string direccionEntrega, string razonSocial) {
            return base.Channel.ObtenerSolicitudesSalidaAsync(idSolicitud, estadoSolicitud, fechaInicio, fechaFin, idEmpleado, tipoSalida, direccionEntrega, razonSocial);
        }
        
        public ETNA.MVC.LogisticaServices.SolicitudSalidaDto ObtenerSolicitudSalida(int idSolicitud) {
            return base.Channel.ObtenerSolicitudSalida(idSolicitud);
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.SolicitudSalidaDto> ObtenerSolicitudSalidaAsync(int idSolicitud) {
            return base.Channel.ObtenerSolicitudSalidaAsync(idSolicitud);
        }
        
        public bool GenerarGuiaSalida(int idSolicitud, int idAlmacen, int idEmpleado) {
            return base.Channel.GenerarGuiaSalida(idSolicitud, idAlmacen, idEmpleado);
        }
        
        public System.Threading.Tasks.Task<bool> GenerarGuiaSalidaAsync(int idSolicitud, int idAlmacen, int idEmpleado) {
            return base.Channel.GenerarGuiaSalidaAsync(idSolicitud, idAlmacen, idEmpleado);
        }
        
        public bool RechazarGuiaSalida(int idSolicitud, string observaciones) {
            return base.Channel.RechazarGuiaSalida(idSolicitud, observaciones);
        }
        
        public System.Threading.Tasks.Task<bool> RechazarGuiaSalidaAsync(int idSolicitud, string observaciones) {
            return base.Channel.RechazarGuiaSalidaAsync(idSolicitud, observaciones);
        }
        
        public ETNA.MVC.LogisticaServices.EmpleadoDto[] ObtenerEmpleados() {
            return base.Channel.ObtenerEmpleados();
        }
        
        public System.Threading.Tasks.Task<ETNA.MVC.LogisticaServices.EmpleadoDto[]> ObtenerEmpleadosAsync() {
            return base.Channel.ObtenerEmpleadosAsync();
        }
    }
}
